name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: xcodebuild -scheme mtoc -jobs 1 -configuration Debug CONFIGURATION_BUILD_DIR=build/Debug ARCHS='x86_64 arm64' ONLY_ACTIVE_ARCH=NO
      - run: xcodebuild -scheme mtoc -jobs 1 -configuration Release CONFIGURATION_BUILD_DIR=build/Release ARCHS='x86_64 arm64' ONLY_ACTIVE_ARCH=NO
      - run: cd build/Debug && zip -qry ocmtoc-$(./mtoc --version)-DEBUG.zip mtoc
      - run: cd build/Release && zip -qry ocmtoc-$(./mtoc --version)-RELEASE.zip mtoc

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/*/*.zip
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@04733e069f2d7f7f0b4aebc4fbdbce8613b03ccd
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*/*.zip
          tag: ${{ github.ref }}
          file_glob: true
